# Generated by Django 2.0.7 on 2018-07-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Steam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=50)),
                ('total_games', models.IntegerField(default=0)),
                ('total_minutes', models.IntegerField(default=0)),
                ('total_hours', models.IntegerField(default=0)),
                ('total_years', models.CharField(max_length=5, null=True)),
                ('help_status', models.CharField(max_length=50, null=True)),
                ('all_games', models.CharField(max_length=100000, null=True)),
                ('filtered_games', models.CharField(max_length=100000, null=True)),
            ],
        ),
    ]
