# Generated by Django 2.0.7 on 2018-07-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Starter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=20)),
            ],
        ),
    ]
