# Generated by Django 2.0.7 on 2018-07-23 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Starter', '0002_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubgStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pubg_id', models.CharField(max_length=50)),
                ('kdr', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Starter.Season')),
            ],
        ),
    ]
