# Generated by Django 2.0.7 on 2018-07-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Starter', '0003_pubgstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubgstat',
            name='kdr',
            field=models.FloatField(),
        ),
    ]
